/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.slusarzwozniak.view;

import com.slusarzwozniak.model.Model;
import com.slusarzwozniak.model.worker.Worker;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Dominik
 */
public class MenageWorkerWorkplacesJFrame extends BasicJFrame {

    /**
     * Creates new form MenageWorkerWorkplacesJFrame
     */
    public MenageWorkerWorkplacesJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableWorkerWorkplaces = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabelWorker = new javax.swing.JLabel();
        jComboBoxWorkplace = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePositions = new javax.swing.JTable();
        jComboBoxWorkplaceDetail = new javax.swing.JComboBox();
        jButtonAddWorkplaceToWorker = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableWorkerWorkplaces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableWorkerWorkplaces);

        jLabel1.setText("Worker:");

        jLabelWorker.setText("worker detail");

        jComboBoxWorkplace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Werehouse", "Shop" }));

        jTablePositions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablePositions);

        jComboBoxWorkplaceDetail.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAddWorkplaceToWorker.setText("Add workplace");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelWorker))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxWorkplace, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxWorkplaceDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAddWorkplaceToWorker)))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelWorker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxWorkplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxWorkplaceDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddWorkplaceToWorker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddWorkplaceToWorker;
    private javax.swing.JComboBox jComboBoxWorkplace;
    private javax.swing.JComboBox jComboBoxWorkplaceDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelWorker;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablePositions;
    private javax.swing.JTable jTableWorkerWorkplaces;
    // End of variables declaration//GEN-END:variables

    public void jComboBoxActionPerformed(ActionListener actionListener){
        this.jComboBoxWorkplace.addActionListener(actionListener);
    }
    
    public JButton getjButtonAddWorkplaceToWorker() {
        return jButtonAddWorkplaceToWorker;
    }

    public void setjButtonAddWorkplaceToWorker(JButton jButtonAddWorkplaceToWorker) {
        this.jButtonAddWorkplaceToWorker = jButtonAddWorkplaceToWorker;
    }

    public JComboBox getjComboBoxWorkplace() {
        return jComboBoxWorkplace;
    }

    public void setjComboBoxWorkplace(JComboBox jComboBoxWorkplace) {
        this.jComboBoxWorkplace = jComboBoxWorkplace;
    }

    public JComboBox getjComboBoxWorkplaceDetail() {
        return jComboBoxWorkplaceDetail;
    }

    public void setjComboBoxWorkplaceDetail(JComboBox jComboBoxWorkplaceDetail) {
        this.jComboBoxWorkplaceDetail = jComboBoxWorkplaceDetail;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabelWorker() {
        return jLabelWorker;
    }

    public void setjLabelWorker(JLabel jLabelWorker) {
        this.jLabelWorker = jLabelWorker;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JTable getjTablePositions() {
        return jTablePositions;
    }

    public void setjTablePositions(JTable jTablePositions) {
        this.jTablePositions = jTablePositions;
    }

    public JTable getjTableWorkerWorkplaces() {
        return jTableWorkerWorkplaces;
    }

    public void setjTableWorkerWorkplaces(JTable jTableWorkerWorkplaces) {
        this.jTableWorkerWorkplaces = jTableWorkerWorkplaces;
    }
    
    @Override
    public void update(Model model) {
       this.jTablePositions.setModel(model.positionsToTable());
    }
    
}
